language: android
android:
    components:
        - build-tools-19.1.0
        - android-10
    licences:
        - '.+'
before_script:
    - android update project -t android-10 -p .
script:
    - ant debug lint
